<?php

if ($block->enable == 'yes') {
    $fedExModuleFlag = 'YES';
    $block->setTemplate('Eniture_StandardBoxSizes::/system/config/boxsizestab.phtml');
    echo $block->getHtml();
} else {
    ?>
        <div class="boxsizes">
            <p>
            <?=
            /* @noEscape */ __(
                'Please visit our store to add the Standard Box Sizes module. (<a href="%1" target="_blank">Learn more</a>)',
                "https://eniture.com/magento2-standard-box-sizes/#documentation"
            )
            ?>
            </p>
        </div>
    <?php
}
