<?php
if ($block->enable == 'yes') {
    ?>
        <script type="text/javascript">
            require(["jquery","domReady!"], function ($) {
                $('#row_fedexQuoteSetting_third_boxSizesQuoteStng').remove();
            });
        </script>
    <?php
} else {
    ?>      
        <div class="boxsizes">
            <p>
            <?=
            /* @noEscape */ __(
                'Click <a href="%1" target="_blank">here</a> to add the Standard Box Sizes module. (<a href="%2" target="_blank">Learn more</a>)',
                "https://eniture.com/magento2-standard-box-sizes/",
                "https://eniture.com/magento2-standard-box-sizes/#documentation"
            )
            ?>
            </p>
        </div>
<?php }
