<script type="text/javascript">
    var fedexSmpkgDSEditAjaxUrl = '<?= /* @noEscape */ $block->editDropshipAjaxCheckUrl() ?>';
    var fedexSmpkgDSDeleteAjaxUrl = '<?= /* @noEscape */ $block->deleteDropshipAjaxCheckUrl() ?>';
</script>
<div class="main_container">
    <h1>
        <?= /* @noEscape */ __('Drop Ships') ?>
    </h1>
    <a href="#delete_dropship_btn" class="delete_dropship_btn hide_drop_val"></a>
    <div id="delete_dropship_btn" class="fedexSmpkg_warehouse_overlay">
        <div class="add_warehouse_popup delete_ds_popup">
            <h2 class="del_hdng">
                <?= /* @noEscape */ __('FedEx Small Packages') ?>
            </h2>
            <p class="delete_p">
                <?= /* @noEscape */ __('Warning! If you delete this location, Drop ship location settings will be disable against products.') ?>
            </p>
            <div class="del_btns">
                <a href="#" class="cancel_delete">
                    <?= /* @noEscape */ __('Cancel') ?>
                </a>
                <a href="#" class="confirm_delete">
                    <?= /* @noEscape */ __('OK') ?>
                </a>
            </div>
        </div>
    </div>

    <a href="#add_dropship_btn" class="add_dropship_btn hide_drop_val" title=<?= /* @noEscape */ __('Add Drop Ship') ?>>
        <?= /* @noEscape */ __('Add') ?>
    </a>
    <div class="warehouse_text ds">
        <p>
            <?= /* @noEscape */ __("Locations that inventory specific items that are drop shipped to the destination. Use the product's settings page to identify it as a drop shipped item and its associated drop ship location. Orders that include drop shipped items will display a single figure for the shipping rate estimate that is equal to the sum of the cheapest option of each shipment required to fulfill the order.") ?>
        </p>
    </div>
    <div class="message message-success success dropship_created">
        <p>
            <strong>
                <?= /* @noEscape */ __('Success! New drop ship added successfully.') ?>
            </strong>
        </p>
    </div>
    <div class="message message-success success dropship_updated">
        <p>
            <strong>
                <?= /* @noEscape */ __('Success! Drop ship updated successfully.') ?>
            </strong>
        </p>
    </div>
    <div class="message message-success success dropship_deleted">
        <p>
            <strong>
                <?= /* @noEscape */ __('Success! Drop ship deleted successfully.') ?>
            </strong>
        </p>
    </div>
    <table class="warehouse" id="append_dropship">
        <thead>
            <tr>
                <th>
                    <?= /* @noEscape */ __('Nickname') ?>
                </th>
                <th>
                    <?= /* @noEscape */ __('City') ?>
                </th>
                <th>
                    <?= /* @noEscape */ __('State') ?>
                </th>
                <th>
                    <?= /* @noEscape */ __('Zip') ?>
                </th>
                <th>
                    <?= /* @noEscape */ __('Country') ?>
                </th>
                <th>
                    <?= /* @noEscape */ __('Action') ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php
                $getDropships   = $block->dataHelper->fetchWarehouseSecData('dropship');
            if ($getDropships) {
                foreach ($getDropships as $r) {
                    ?>
                    <tr id="row_<?= /* @noEscape */ $r['warehouse_id']; ?>" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>">
                            <td>
                            <?= /* @noEscape */ $r['nickname']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['city']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['state']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['zip']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['country']; ?>
                            </td>
                            <td>
                            <a href="javascript(0)" class="edit_dropship" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Edit')?>" onclick="return fedexSmpkgEditDropship(<?= /* @noEscape */ $r['warehouse_id']; ?>, fedexSmpkgDSEditAjaxUrl)">
                                <?= __('Edit') ?>
                            </a> / <a href="javascript(0)" onclick="return fedexSmpkgDeleteDropship(<?= /* @noEscape */ $r['warehouse_id']; ?>, fedexSmpkgDSDeleteAjaxUrl);" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Delete')?>">
                                <?= /* @noEscape */ __('Delete') ?>
                                </a>
                            </td>
                        </tr>
            <?php
                }
            }
            ?>
        </tbody>
    </table>
</div>
     <!-- Add Popup for new dropship -->
    <div id="add_dropship_btn" class="fedexSmpkg_warehouse_overlay">
        <div class="add_warehouse_popup ds-popup dropshipSection">
            <h2 class="dropship_heading">
                <?= /* @noEscape */ __('Drop Ship') ?>
            </h2>
            <a class="close close-ds" href="#">&times;</a>
            <div class="content FedEx_small_warehouseFormContent">
                <div class="already_exist">
                    <strong>
                        <?= /* @noEscape */ __('Error!') ?>
                    </strong> 
                    <?= /* @noEscape */ __('Drop ship already exists.') ?>
                </div>
                <div class="not_allowed">
                    <strong>
                        <?= /* @noEscape */ __('Error!') ?>
                    </strong> 
                    <?= /* @noEscape */ __('Please select US or CA address.') ?>
                </div>
                <div class="api_error"></div>
                
                <div id="fedexSmpkgDropshipForm">
                    <input type="hidden" name="edit_dropship_form_id" value="" id="edit_dropship_form_id">
                    <div class="add_warehouse_input ds-input">
                        <span>
                            <?= /* @noEscape */ __('Nickname') ?>
                        </span>
                        <input type="text" title=<?= /* @noEscape */ __('Nickname') ?> value="" data-optional="1" name="fedexSmpkg_dropship_nickname" placeholder="Nickname" id="fedexSmpkg_dropship_nickname">
                    </div>
                    <div class="add_warehouse_input">
                        <label for="origin_zip">
                            <?= /* @noEscape */ __('Zip') ?>
                        </label>
                        <input type="text" title=<?= /* @noEscape */ __('Zip') ?> maxlength="7" value="" name="fedexSmpkg_dropship_zip" placeholder="30214" id="fedexSmpkg_dropship_zip" onchange="return fedexSmpkgGetAddressFromZip('<?= /* @noEscape */ $block->getAjaxDsAddressUrl() ?>', this, /* @noEscape */ fedexSmpkgGetDsAddressResSettings)" data-action="dropship_get_address">
                    </div>

                    <div class="add_warehouse_input city_input">
                        <label for="origin_city">
                            <?= /* @noEscape */ __('City') ?>
                        </label>
                        <input type="text" title=<?= /* @noEscape */ __('City') ?> class="alphaonly" value="" name="dropship_city" placeholder="Fayetteville" id="dropship_city">
                    </div>

                    <div class="add_warehouse_input city_select" style="display:none;">
                        <label for="origin_city">
                                <?= /* @noEscape */ __('City') ?>
                        </label>
                        <select id="dropship_actname" value=""></select>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="origin_state">
                            <?= /* @noEscape */ __('State') ?>
                        </label>
                        <input type="text" title=<?= /* @noEscape */ __('State') ?> maxlength="2" class="alphaonly" value="" name="dropship_state" placeholder="GA" id="dropship_state">
                    </div>

                    <div class="add_warehouse_input">
                        <label for="origin_country">
                            <?= /* @noEscape */ __('Country') ?>
                        </label>
                        <input type="text" title=<?= /* @noEscape */ __('Country') ?> maxlength="2" class="alphaonly" name="dropship_country" value="" placeholder="US" id="dropship_country">
                        <input type="hidden" name="dropship_location" value="dropship" id="dropship_location">
                    </div>
                    
                    <div class="form-btns">
                        <input type="submit" name="submit_dropship" value="Save" class="save_warehouse_form" onclick="return fedexSmpkgSaveDropship('<?= /* @noEscape */ $block->saveDropshipAjaxCheckUrl() ?>');">
                    </div>
                </div>
            </div>
        </div>
    </div>
     
