<?php

$formData = [
    'divElement'       =>  '#success',
];
$serializedFormData = $block->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<div class="pp-buttons-container">
    <button class="primary" id="<?= /* @noEscape */ $block->getId() ?>" onclick="return fedexSmpkgTestConn('<?= /* @noEscape */ $block->getAjaxCheckUrl() ?>');">
        <span>
            <span>
                <span>
                    <?= /* @noEscape */ $block->escapeHtml($block->getButtonLabel()); ?>
                </span>
            </span>
        </span>
    </button>
</div>

<!-- Display Success Message -->
<div id="successCon" style="display: none;" class="test_connection_sccs">
    <strong>
        <?=
            /* @noEscape */ __('Success!')
        ?>
    </strong>
    <span id="succesText">
        <?=
            /* @noEscape */ __('The test resulted in a successful connection.')
        ?>
    </span>
</div>

<!-- Display Error Message -->
<div id="failCon" style="display: none;" class="test_connection_err">
    <strong>
        <?=
            /* @noEscape */ __('Error!')
        ?> 
    </strong>
    <span id="errorText">
        <?=
            /* @noEscape */ __('The credentials entered did not result in a successful test. Confirm your credentials and try again.')
        ?>
    </span>
</div>
