<?php

$formData = [
    'divElement'       =>  '#success',
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);

$planMsg = $block->fedexSmallPlanNotice();
?>
<script type="text/javascript">
    require([ 'jquery', 'domReady!'], function($){
        var carrierdiv = '#fedexconnsettings_first-head';
        currentPlanNote($, '<?php echo $planMsg; ?>', carrierdiv);
    });
</script>
<div class="pp-buttons-container">
    <button class="primary" id="<?= /* @noEscape */ $block->getId() ?>" onclick="return fedexSmpkgTestConn('<?= /* @noEscape */ $block->getAjaxCheckUrl() ?>');">
        <span>
            <span>
                <span>
                    <?= /* @noEscape */ $block->escapeHtml($block->getButtonLabel()); ?>
                </span>
            </span>
        </span>
    </button>
</div>

<!-- Display Success Message -->
<div id="fedexsuccessCon"  style="display: none; margin-top: 20px;"class="message message-success success">
    <div data-ui-id="messages-message-success">
        <strong>
            <?=
                /* @noEscape */ __('Success!')
            ?>
        </strong>
        <span id="succesText">
            <?=
            /* @noEscape */ __('The test resulted in a successful connection.')
            ?>
        </span>
    </div>
</div>

<!-- Display Error Message -->
<div id="fedexfailCon"  style="display: none; margin-top: 20px;"class="message message-error error">
    <div data-ui-id="messages-message-error">
        <strong>
            <?=
                /* @noEscape */ __('Error!')
            ?>
        </strong>
        <span id="errorText">
            <?=
            /* @noEscape */ __('The credentials entered did not result in a successful test. Confirm your credentials and try again.')
            ?>
        </span>
    </div>
</div>

