<?php
    $plan = $block->getCurrentPlan();
    $advancedPlan = false;
    $class = 'disabledDiv';
    $disableInput = 'disabled="disabled"';
if ($plan == 1) {
    $advancedPlan = true;
    $class = '';
    $disableInput = '';
}
?>

<script>
    require([ 'jquery', 'domReady!'], function($){
            var carrierdiv = '#fedexWarehouse_second-head';
            currentPlanNote($, '<?php echo $block->fedexSmallPlanNotice(); ?>', carrierdiv);
            
            var canAddWh = <?php echo $block->addWhRestriction(); ?>;
            addWarehouseRestriction(canAddWh);
        });
    var fedexSmpkgWHEditAjaxUrl = '<?= /* @noEscape */ $block->editWarehouseAjaxCall() ?>';
    var fedexSmpkgWHDeleteAjaxUrl = '<?= /* @noEscape */ $block->deleteWarehouseAjaxCall() ?>';    
</script>

<div class="main_container">
    <h1>
        <?=
            /* @noEscape */ __('Warehouses')
        ?>
    </h1>
    <a href="#add_warehouse_btn" class="add_warehouse_btn hide_val" name="avc" title=<?= /* @noEscape */ __('Add Warehouse') ?>>
        <?=
            /* @noEscape */ __('Add')
        ?>
    </a>
    <div class="warehouse_text wh">
        <p>
            <?=
                /* @noEscape */ __('Warehouses that inventory all products not otherwise identified as drop shipped items. The warehouse with the lowest shipping cost to the destination is used for quoting purposes.')
            ?>
        </p>
    </div>
    <div class="message message-success success warehouse_created">
        <p>
            <strong>
                <?=
                /* @noEscape */ __('Success! ')
                ?>
            </strong>
            <?=
            /* @noEscape */ __('New warehouse added successfully.')
            ?>
        </p>
    </div>
    <div class="message message-success success warehouse_updated">
        <p>
            <strong>
                <?=
                /* @noEscape */ __('Success! ')
                ?>
            </strong>
            <?=
            /* @noEscape */ __('Warehouse updated successfully.')
            ?>
        </p>
    </div>
    <div class="message message-success success warehouse_deleted">
        <p>
            <strong>
                <?=
                /* @noEscape */ __('Success! ')
                ?>
            </strong>
            <?=
            /* @noEscape */ __('Warehouse deleted successfully.')
            ?>
        </p>
    </div>

    <table class="warehouse" id="append_warehouse">
        <thead>
            <tr>
                <th>
                    <?=
                        /* @noEscape */ __('City')
                    ?>
                </th>
                <th>
                    <?=
                        /* @noEscape */ __('State')
                    ?>
                </th>
                <th>
                    <?=
                        /* @noEscape */ __('Zip')
                    ?>
                </th>
                <th>
                    <?=
                        /* @noEscape */ __('Country')
                    ?>
                </th>
                <th>
                    <?=
                        /* @noEscape */ __('Action')
                    ?>
                </th>
            </tr>
        </thead>
         <tbody>
            <?php
                $getWarehouses  = $block->dataHelper->fetchWarehouseSecData('warehouse');
            if ($getWarehouses) {
                foreach ($getWarehouses as $r) {
                ?>
                    <tr id="row_<?= /* @noEscape */ $r['warehouse_id']; ?>" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>">
                            <td>
                            <?= /* @noEscape */ $r['city']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['state']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['zip']; ?>
                            </td>
                            <td>
                            <?= /* @noEscape */ $r['country']; ?>
                            </td>
                            <td>
                            <a href="javascript(0)" class="edit_warehouse" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>;" title="<?= /* @noEscape */ __('Edit') ?>" onclick="return fedexSmpkgEditWarehouse(<?= /* @noEscape */ $r['warehouse_id']; ?>, fedexSmpkgWHEditAjaxUrl);">
                                <?= /* @noEscape */ __('Edit') ?>
                            </a> | <a href="javascript(0)" onclick="return fedexSmpkgDeleteWarehouse(<?= /* @noEscape */ $r['warehouse_id']; ?>, fedexSmpkgWHDeleteAjaxUrl);" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Delete') ?>">
                                <?= /* @noEscape */ __('Delete') ?>
                                </a>
                            </td>
                        </tr>
                <?php   }
            }
            ?>
        </tbody>
    </table>

    <hr class="warehouse_hr">
</div>
<!-- Add Popup for new warehouse -->
<div id="add_warehouse_btn" class="fedexSmpkg_warehouse_overlay">
    <div class="add_warehouse_popup warehouseSection">
        <h2 class="warehouse_heading">
            <?=
                /* @noEscape */ __('Warehouse')
            ?>
        </h2>
        <a class="close" href="#">&times;</a>

        <div class="content FedEx_small_warehouseFormContent">
            <div class="message message-error error already_exist">
                <div data-ui-id="messages-message-error">
                    <strong>
                        <?=
                            /* @noEscape */ __('Error!')
                        ?> 
                    </strong>
                        <?=
                            /* @noEscape */ __('Warehouse already exists.')
                        ?>
                </div>
            </div>
            
            <div class="message message-error error not_allowed">
                <div data-ui-id="messages-message-error">
                    <strong>
                        <?=
                            /* @noEscape */ __('Error!')
                        ?> 
                    </strong>
                        <?=
                            /* @noEscape */ __('Please select US or CA address.')
                        ?>
                </div>
            </div>
            
            <div class="message message-error error api_error">
                <div data-ui-id="messages-message-error">
                    <strong>
                        <?=
                            /* @noEscape */ __('Error!')
                        ?> 
                    </strong>
                        <?=
                            /* @noEscape */ __('Request is not processed, please enter Warehouse information manually.')
                        ?>
                </div>
            </div>

            <div id="fedexSmpkgWarehouseForm">
                <input type="hidden" name="edit_form_id" value="" id="edit_form_id">
                <div class="add_warehouse_input">
                    <label for="origin_zip">
                        <?= /* @noEscape */ __('Zip') ?>
                    </label>
                    <input type="text" title="<?= /* @noEscape */ __('Zip') ?>" maxlength="7" value="" name="fedexSmpkg_warehouse_zip" placeholder="30214" id="fedexSmpkg_warehouse_zip" onchange="return fedexSmpkgGetAddressFromZip('<?= /* @noEscape */ $block->getAjaxAddressUrl() ?>', this,fedexSmpkgGetAddressResSettings)" data-action="warehouse_get_address">
                    <span class="err"></span>
                </div>

                <div class="add_warehouse_input city_input">
                    <label for="origin_city">
                        <?= /* @noEscape */ __('City') ?>
                    </label>
                    <input type="text" title=<?= /* @noEscape */ __('City') ?> class="alphaonly" value="" name="warehouse_origin_city" placeholder="Fayetteville" id="warehouse_origin_city">
                    <span class="err"></span>
                </div>

                <div class="add_warehouse_input city_select" style="display:none;">
                    <label for="origin_city">
                        <?= /* @noEscape */ __('City') ?>
                    </label>
                    <select id="actname" value=""></select>
                    <span class="err"></span>
                </div>

                <div class="add_warehouse_input">
                    <label for="origin_state">
                        <?= /* @noEscape */ __('State') ?>
                    </label>
                    <input type="text" title=<?= /* @noEscape */ __('State') ?> class="alphaonly" maxlength="2" value="" name="warehouse_origin_state" placeholder="GA" id="warehouse_origin_state">
                    <span class="err"></span>
                </div>

                <div class="add_warehouse_input">
                    <label for="origin_country">
                        <?= /* @noEscape */ __('Country') ?>
                    </label>
                    <input type="text" title=<?= /* @noEscape */ __('Country') ?> class="alphaonly" maxlength="2" name="warehouse_origin_country" value="" placeholder="US" id="warehouse_origin_country">
                    <input type="hidden" name="warehouse_location" value="warehouse" id="warehouse_location">
                    <span class="err"></span>
                </div>
                
                <!--In store Pickup Section-->

                <div class="row" style="clear: both">
                    <h2 class="is_heading_left" id="wh_is_heading_left">
                        <?=
                        /* @noEscape */ __('In-store Pick Up')
                        ?>
                    </h2>
                    <?php if (!$advancedPlan) : ?>
                    <a class="is_heading_right">
                        <?=
                        /* @noEscape */ __('Advanced Plan Required')
                        ?>
                    </a>
                    <?php endif; ?>
                </div>
                <div class="message message-error error wh-instore-miles-postal-err">
                    <div data-ui-id="messages-message-error">
                        <strong>
                            <?=
                                /* @noEscape */ __('Error!')
                            ?> 
                        </strong>
                            <?=
                                /* @noEscape */ __('You must provide Miles or Postal Code.')
                            ?>
                    </div>
                </div>
                
                <div id="disableddiv" class="<?= $class ?>">
                    <div class="add_warehouse_input">
                        <label for="enable_instore_pickup">
                            <?= /* @noEscape */ __('Enable In-Store Pick Up') ?>
                        </label>
                        <input type="checkbox" title="<?= /* @noEscape */ __('Enable In-Store Pick Up') ?>" class="enable_checkbox" name="enable_instore_pickup" value="" id="enable_instore_pickup" <?= $disableInput ?>>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="within_miles">
                            <?= /* @noEscape */ __('Offer if address is within (miles)') ?> :
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Offer if address is within (miles)') ?>" class="numberonly" maxlength="4" name="within_miles" value=""  id="within_miles" <?= $disableInput ?> onpaste="return false">
                        <span class="err"></span>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="postcode_match">
                            <?= /* @noEscape */ __('Offer if postal code matches') ?> :
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Offer if postal code matches') ?>" maxlength="7" value=""  name="postcode_match"  id="postcode_match" data-role="<?= $advancedPlan? 'tagsinput': ''; ?>" <?= $disableInput ?>>
                        <span class="err"></span>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="checkout_descp">
                            <?= /* @noEscape */ __('Check Out Description') ?> :
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Check Out Description') ?>" class="alphaonly" maxlength="100" name="checkout_descp" placeholder="In-store pick up" id="checkout_descp" <?= $disableInput ?>>
                        <span class="err"></span>
                    </div>
                </div>
                <!--In store Pickup Section End-->

                <!--Local Delivery Section-->

                <div class="row" style="clear: both">
                    <h2 class="ld_heading_left" id="wh_ld_heading_left" >
                        <?=
                        /* @noEscape */ __('Local Delivery')
                        ?>
                    </h2>
                    <?php if (!$advancedPlan) : ?>
                    <a class="ld_heading_right">
                        <?=
                        /* @noEscape */ __('Advanced Plan Required')
                        ?>
                    </a>
                    <?php endif;?>
                </div>
                <div class="message message-error error wh-local-miles-postals-err">
                    <div data-ui-id="messages-message-error">
                        <strong>
                            <?=
                                /* @noEscape */ __('Error!')
                            ?> 
                        </strong>
                            <?=
                                /* @noEscape */ __('You must provide Miles or Postal Code.')
                            ?>
                    </div>
                </div>
                <!--Local Delivery Section Start-->
                <div id="disableddiv" class="<?= $class ?>">

                    <div class="add_warehouse_input">
                        <label for="enable_local_delivery">
                            <?= /* @noEscape */ __('Enable Local Delivery') ?>
                        </label>
                        <input type="checkbox" title="<?= /* @noEscape */ __('Enable Local Delivery') ?>" class="enable_checkbox" name="enable_local_delivery" value="" id="enable_local_delivery" <?= $disableInput ?>>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="ld_within_miles">
                            <?= /* @noEscape */ __('Offer if address is within (miles)') ?> :
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Offer if address is within (miles)') ?>" class="numberonly" maxlength="4" name="ld_within_miles" value=""  id="ld_within_miles" <?= $disableInput ?> onpaste="return false">
                        <span class="err"></span>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="ld_postcode_match">
                            <?= /* @noEscape */ __('Offer if postal code matches') ?> :
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Offer if postal code matches') ?>" maxlength="7" value="" data-role="<?= $advancedPlan? 'tagsinput': ''; ?>" name="ld_postcode_match"  id="ld_postcode_match" <?= $disableInput ?>>
                        <span class="err"></span>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="ld_checkout_descp">
                            <?= /* @noEscape */ __('Check Out Description') ?> :
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Check Out Description') ?>" class="alphaonly" maxlength="100" name="ld_checkout_descp" placeholder="Local delivery" id="ld_checkout_descp" <?= $disableInput ?>>
                        <span class="err"></span>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="ld_fee">
                            <?= /* @noEscape */ __('Local Delivery Fee') ?>
                        </label>
                        <input type="text" title="<?= /* @noEscape */ __('Fee') ?>" class="decimalonly" maxlength="7" name="ld_fee" value=""  id="ld_fee" <?= $disableInput ?> onpaste="return false">
                        <span class="err"></span>
                    </div>

                    <div class="add_warehouse_input">
                        <label for="ld_sup_rates">
                            <?= /* @noEscape */ __('Suppress other rates') ?>
                        <div class="suppressTooltip">[ ? ]
                            <span class="suppressTooltiptext"><?= /* @noEscape */ __("This setting only suppresses rates that would otherwise be returned by the Eniture Technology products.") ?></span>
                        </div> 
                        </label>
                        <input type="checkbox" title="<?= /* @noEscape */ __('Suppress other rates') ?>" class="enable_checkbox" name="ld_sup_rates" id="ld_sup_rates" <?= $disableInput ?>>
                    </div>
                </div>
                <!--Local Delivery Section End-->

                <div class="form-btns">
                    <input type="submit" name="warehouse_submit_warehouse" value="Save" onclick="return fedexSmpkgSaveWarehouseData('<?= /* @noEscape */ $block->savefedexSmpkgWarehouseAjaxCall() ?>');" class="save_warehouse_form">
                </div>
            </div>
        </div>
    </div>
</div>
