<section class="admin__page-section custom-tab-content">
    <h1>Additional Order Details</h1>
    <?php
    $order = $block->getOrder();

    $orderDetailData = $order->getData('order_detail_data');
    $orderDetailData = isset($orderDetailData)?json_decode($orderDetailData, true):null;

    if ($orderDetailData == null) {
        $shimentNumber = 1;
        foreach ($orderDetailData['shipmentData'] as $key => $order) {
            if (isset($order) && !empty($order)) {
                $residential = $liftGate = false;
                $resi = $order['quotes']['residentialDelivery'] ?? false;
                $title = (isset($order['quotes']['title'])) ? $order['quotes']['title'] . ' :' : '';
                $rate = (isset($order['quotes']['rate'])) ? number_format($order['quotes']['rate'], 2, '.', '') : '0.00';

                if ($shimentNumber > 1) { ?>
                    <hr class="order-info-hr">
                <?php } ?>

                <div class="order-detail-block">
                    <h4 class='order-detail-hdng'>
                        Shipment <?= $shimentNumber ?> > Origin & Services
                    </h4>

                    <div class="order-shipment-block">
                <span class="list-item">
                    <?= ucfirst($order['origin']['location']) . ': ' . $order['origin']['senderCity'] . ', ' . $order['origin']['senderState'] . ' ' . $order['origin']['senderZip'] . ', ' . $order['origin']['senderCountryCode'] ?>
                    <span class="list-item">
                        <?= $title . ' $' . $rate ?>
                    </span>
                </span>
                    </div>


                    <?php
                    if (isset($order['quotes']['code'])) {
                        if (stripos($order['quotes']['code'], "HOAT") === false) {
                            $residential = ($orderDetailData['residentialDelivery'] || $resi) ? 'Residential Delivery' : false;
                            $liftGate = $orderDetailData['liftGateDelivery'] ?? false;
                            if ($liftGate) {
                                $liftGate = $liftGate['always'] || $liftGate['asOption'] || $liftGate['residentialLiftgate'] == 'yes' ? 'Liftgate Delivery' : false;
                            }
                        }
                    }
                    $lineItems = $order['item'];
                    $findHazardous = array_column($lineItems, 'isHazmatLineItem');
                    $hazordus = ($findHazardous[0] == 'Y') ? 'Hazardous Material' : '';

                    if ($residential || $hazordus || $liftGate) { ?>
                        <h4 class='order-detail-hdng'>Additional Information</h4>
                        <div class="order-additionalInfo-block">

                            <?php
                            if ($residential) { ?>
                                <span class="list-item">
                                    <?= $residential ?>
                                    </span>

                            <?php }
                            if ($hazordus) { ?>
                                <span class="list-item">
                                    <?= $hazordus ?>
                                    </span>

                            <?php }

                            if ($liftGate) { ?>
                                <span class="list-item">
                                    <?= $liftGate ?>
                                    </span>

                            <?php } ?>
                        </div>
                    <?php } ?>

                    <h4 class='order-detail-hdng'>
                        Shipment <?= $shimentNumber ?> > items
                    </h4>

                    <?php foreach ($order['item'] as $key => $lineItem) { ?>
                        <div class="order-item-block">
                            <span class="list-item">
                                <?= $lineItem['piecesOfLineItem'] . ' x ' . $lineItem['lineItemName'] ?>
                            </span>
                        </div>

                    <?php } ?>

                    <!-- Clear the float effect -->
                    <div class="en-clear"></div>
                </div>
            <?php }
            $shimentNumber++;
        }
    } else { ?>
        <h4>
            <?= /* @noEscape */ "No additional details are found!"; ?>
        </h4>
    <?php } ?>
</section>
